const KEY="retailmate_v01";
const db=JSON.parse(localStorage.getItem(KEY)||'{"products":[],"sales":[],"purchases":[],"expenses":[],"credits":[]}');
const M=n=>"GH₵"+Number(n||0).toFixed(2), D=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(KEY,JSON.stringify(db));summary()}
function summary(){let d=D(),s=db.sales.filter(x=>x.date===d),rev=s.reduce((a,x)=>a+x.total,0),cost=s.reduce((a,x)=>a+x.cost,0),e=db.expenses.filter(x=>x.date===d).reduce((a,x)=>a+x.amount,0),c=db.credits.filter(x=>!x.paid).reduce((a,x)=>a+x.amount,0);sales.textContent=M(rev);expenses.textContent=M(e);credit.textContent=M(c);profit.textContent=M(rev-cost-e)}
function opts(){return db.products.map((p,i)=>`<option value="${i}">${p.name} (${p.qty} left)</option>`).join("")}
function show(v){let el=document.getElementById("view");
if(v==="buy"){el.innerHTML=`<h2>I Bought Goods</h2><div class="form">
<label>Product<input id="n" placeholder="e.g. Geisha Soap"></label><label>Quantity<input id="q" type="number" min="1" value="1"></label>
<label>Cost per item<input id="c" type="number" step=".01"></label><label>Selling price<input id="sp" type="number" step=".01"></label>
<button class="primary" onclick="buy()">Save Purchase</button></div>`}
else if(v==="sell"){el.innerHTML=`<h2>Sell</h2><div class="form"><label>Product<select id="p">${opts()||"<option>No products yet</option>"}</select></label>
<label>Quantity<input id="sq" type="number" min="1" value="1"></label><label>Payment<select id="pay"><option>Cash</option><option>Mobile Money</option><option>Credit</option></select></label>
<label>Customer name for credit<input id="cust"></label><button class="primary" onclick="sellItem()">Record Sale</button></div>`}
else if(v==="stock"){el.innerHTML=`<h2>My Stock</h2>${db.products.length?db.products.map(p=>`<div class="item"><div><b>${p.name}</b><small>Cost ${M(p.cost)} · Sell ${M(p.sell)}</small></div><span class="pill">${p.qty} left</span></div>`).join(""):'<div class="empty">No stock yet.</div>'}`}
else if(v==="expense"){el.innerHTML=`<h2>Expense</h2><div class="form"><label>Description<input id="ed"></label><label>Amount<input id="ea" type="number" step=".01"></label><button class="primary" onclick="addExpense()">Record Expense</button></div>`}
else if(v==="credit"){let a=db.credits.filter(x=>!x.paid);el.innerHTML=`<h2>Customer Owes Me</h2>${a.length?a.map(x=>`<div class="item"><div><b>${x.customer}</b><small>${x.product} · ${x.date}</small></div><div><b>${M(x.amount)}</b><br><button onclick="paid(${db.credits.indexOf(x)})">Mark paid</button></div></div>`).join(""):'<div class="empty">No unpaid credit.</div>'}`}
else if(v==="report"){let d=D(),s=db.sales.filter(x=>x.date===d),rev=s.reduce((a,x)=>a+x.total,0),cost=s.reduce((a,x)=>a+x.cost,0),e=db.expenses.filter(x=>x.date===d).reduce((a,x)=>a+x.amount,0),cash=s.filter(x=>x.payment==="Cash").reduce((a,x)=>a+x.total,0),momo=s.filter(x=>x.payment==="Mobile Money").reduce((a,x)=>a+x.total,0),cr=s.filter(x=>x.payment==="Credit").reduce((a,x)=>a+x.total,0);el.innerHTML=`<h2>My Business — Today</h2><div class="report"><div><small>Sales</small><b>${M(rev)}</b></div><div><small>Est. profit</small><b>${M(rev-cost-e)}</b></div><div><small>Cash</small><b>${M(cash)}</b></div><div><small>Mobile Money</small><b>${M(momo)}</b></div><div><small>Credit sales</small><b>${M(cr)}</b></div><div><small>Expenses</small><b>${M(e)}</b></div></div>`}}
function buy(){let name=n.value.trim(),qty=+q.value,cost=+c.value,sell=+sp.value;if(!name||qty<1)return alert("Complete the details.");let p=db.products.find(x=>x.name.toLowerCase()===name.toLowerCase());if(p){p.qty+=qty;p.cost=cost;p.sell=sell}else db.products.push({name,qty,cost,sell});db.purchases.push({date:D(),name,qty,cost,total:qty*cost});save();show("stock")}
function sellItem(){let i=+p.value,qv=+sq.value,x=db.products[i];if(!x||qv<1)return alert("Add stock first.");if(qv>x.qty)return alert("Not enough stock.");let payment=pay.value,total=qv*x.sell;db.sales.push({date:D(),product:x.name,qty:qv,total,cost:qv*x.cost,payment});x.qty-=qv;if(payment==="Credit")db.credits.push({date:D(),customer:cust.value.trim()||"Unnamed customer",product:x.name,amount:total,paid:false});save();show("sell")}
function addExpense(){let amount=+ea.value;if(amount<=0)return alert("Enter an amount.");db.expenses.push({date:D(),description:ed.value.trim()||"Expense",amount});save();show("expense")}
function paid(i){db.credits[i].paid=true;save();show("credit")}
function net(){document.getElementById("net").textContent=navigator.onLine?"Online · saved locally":"Offline · still working"}window.addEventListener("online",net);window.addEventListener("offline",net);net();summary();show("sell");if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");