(() => {
'use strict';
const VERSION='0.3.2', KEY='retailmate_ghana_v032';
const BASE={settings:{businessName:'My Shop',lowStock:5},products:[],sales:[],purchases:[],expenses:[],credits:[]};
const $=id=>document.getElementById(id), clone=o=>JSON.parse(JSON.stringify(o)), today=()=>new Date().toISOString().slice(0,10), money=n=>'GH₵'+Number(n||0).toFixed(2);
const makeId=()=>{try{if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID()}catch(e){}return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function loadDB(){try{const raw=localStorage.getItem(KEY);if(!raw)return clone(BASE);const p=JSON.parse(raw);return{settings:{...BASE.settings,...(p.settings||{})},products:Array.isArray(p.products)?p.products:[],sales:Array.isArray(p.sales)?p.sales:[],purchases:Array.isArray(p.purchases)?p.purchases:[],expenses:Array.isArray(p.expenses)?p.expenses:[],credits:Array.isArray(p.credits)?p.credits:[]}}catch(e){return clone(BASE)}}
let db=loadDB();
function saveDB(){localStorage.setItem(KEY,JSON.stringify(db));refreshSummary()}
function totals(){const d=today(),sales=db.sales.filter(x=>x.date===d),revenue=sales.reduce((a,x)=>a+Number(x.total||0),0),cost=sales.reduce((a,x)=>a+Number(x.cost||0),0),expenses=db.expenses.filter(x=>x.date===d).reduce((a,x)=>a+Number(x.amount||0),0),credit=db.credits.filter(x=>!x.paid).reduce((a,x)=>a+Number(x.amount||0),0);return{sales,revenue,cost,expenses,credit,profit:revenue-cost-expenses}}
function refreshSummary(){const t=totals();$('businessName').textContent=db.settings.businessName||'My Shop';$('salesToday').textContent=money(t.revenue);$('expensesToday').textContent=money(t.expenses);$('creditOwed').textContent=money(t.credit);$('profitToday').textContent=money(t.profit);$('networkStatus').textContent=navigator.onLine?'Online • saved locally':'Offline • saved locally'}
function setStatus(t,k='ok'){const el=$('appStatus');el.textContent=t;el.className='app-status '+k}
function productOptions(){return db.products.map((p,i)=>`<option value="${i}">${esc(p.name)} (${Number(p.qty||0)} left)</option>`).join('')}
function showStock(){const h=db.products.length?db.products.map(p=>`<div class="item"><div><b>${esc(p.name)}</b><small>Cost ${money(p.cost)} • Sell ${money(p.sell)}</small></div><span class="badge">${Number(p.qty||0)} left</span></div>`).join(''):'<div class="empty"><strong>No stock yet.</strong>Tap “I Bought Goods” to add your first product.</div>';$('view').innerHTML=`<h2>My Stock</h2><div class="list">${h}</div>`}
function showSell(){if(!db.products.length){$('view').innerHTML='<h2>Sell</h2><div class="empty"><strong>No products available.</strong>Add stock first.</div>';return}$('view').innerHTML=`<h2>Sell</h2><div class="form"><label>Product<select id="saleProduct">${productOptions()}</select></label><label>Quantity<input id="saleQty" type="number" min="1" value="1"></label><label>Payment<select id="salePayment"><option>Cash</option><option>Mobile Money</option><option>Credit</option></select></label><label>Customer name<input id="saleCustomer" placeholder="Required for credit"></label><button id="recordSaleBtn" class="primary" type="button">Record Sale</button></div>`;$('recordSaleBtn').addEventListener('click',recordSale)}
function showBuy(){$('view').innerHTML=`<h2>I Bought Goods</h2><div class="form"><label>Product name<input id="buyName" placeholder="e.g. Milo 400g"></label><label>Quantity<input id="buyQty" type="number" min="1" value="1"></label><label>Cost per item<input id="buyCost" type="number" min="0" step="0.01"></label><label>Selling price<input id="buySell" type="number" min="0" step="0.01"></label><button id="recordPurchaseBtn" class="primary" type="button">Save Purchase</button></div>`;$('recordPurchaseBtn').addEventListener('click',recordPurchase)}
function showExpense(){$('view').innerHTML=`<h2>Expense</h2><div class="form"><label>Description<input id="expenseDescription" placeholder="e.g. Transport"></label><label>Amount<input id="expenseAmount" type="number" min="0.01" step="0.01"></label><button id="recordExpenseBtn" class="primary" type="button">Record Expense</button></div>`;$('recordExpenseBtn').addEventListener('click',recordExpense)}
function showCredit(){const open=db.credits.filter(x=>!x.paid);$('view').innerHTML=`<h2>Customer Owes Me</h2>${open.length?open.map(c=>`<div class="item"><div><b>${esc(c.customer)}</b><small>${esc(c.product)} • ${c.date}</small></div><div><b>${money(c.amount)}</b><br><button class="secondary mark-paid" data-id="${c.id}" type="button">Mark paid</button></div></div>`).join(''):'<div class="empty"><strong>No unpaid credit.</strong></div>'}`;document.querySelectorAll('.mark-paid').forEach(b=>b.addEventListener('click',()=>markPaid(b.dataset.id)))}
function showBusiness(){const t=totals(),cash=t.sales.filter(x=>x.payment==='Cash').reduce((a,x)=>a+Number(x.total||0),0),momo=t.sales.filter(x=>x.payment==='Mobile Money').reduce((a,x)=>a+Number(x.total||0),0),credit=t.sales.filter(x=>x.payment==='Credit').reduce((a,x)=>a+Number(x.total||0),0);$('view').innerHTML=`<h2>My Business</h2><div class="report"><div><small>Sales</small><b>${money(t.revenue)}</b></div><div><small>Profit</small><b>${money(t.profit)}</b></div><div><small>Cash</small><b>${money(cash)}</b></div><div><small>Mobile Money</small><b>${money(momo)}</b></div><div><small>Credit sales</small><b>${money(credit)}</b></div><div><small>Expenses</small><b>${money(t.expenses)}</b></div></div>`}
function showDatabase(){const bytes=new Blob([JSON.stringify(db)]).size;$('view').innerHTML=`<h2>Database Management</h2><div class="notice">Your RetailMate database is stored locally on this device. Export backups regularly until cloud sync is added.</div><div class="dbgrid"><div class="dbcard"><small>Products</small><b>${db.products.length}</b></div><div class="dbcard"><small>Sales</small><b>${db.sales.length}</b></div><div class="dbcard"><small>Purchases</small><b>${db.purchases.length}</b></div><div class="dbcard"><small>Database size</small><b>${(bytes/1024).toFixed(1)} KB</b></div></div><div class="dbactions"><button id="exportBtn" class="primary" type="button">Export Backup</button><button id="restoreBtn" class="secondary" type="button">Restore Backup</button><button id="clearBtn" class="danger" type="button">Clear Database</button></div>`;$('exportBtn').addEventListener('click',exportDB);$('restoreBtn').addEventListener('click',()=>$('importFile').click());$('clearBtn').addEventListener('click',clearDB)}
function recordPurchase(){const name=$('buyName').value.trim(),qty=Number($('buyQty').value),cost=Number($('buyCost').value),sell=Number($('buySell').value);if(!name||qty<1||cost<0||sell<0)return alert('Complete the product details.');let p=db.products.find(x=>String(x.name).toLowerCase()===name.toLowerCase());if(p){p.qty=Number(p.qty||0)+qty;p.cost=cost;p.sell=sell}else db.products.push({id:makeId(),name,qty,cost,sell});db.purchases.push({id:makeId(),date:today(),product:name,qty,cost,total:qty*cost});saveDB();showStock()}
function recordSale(){const p=db.products[Number($('saleProduct').value)],qty=Number($('saleQty').value),payment=$('salePayment').value,customer=$('saleCustomer').value.trim();if(!p||qty<1)return alert('Choose a valid product and quantity.');if(qty>Number(p.qty||0))return alert('Not enough stock.');if(payment==='Credit'&&!customer)return alert('Enter the customer name.');const total=qty*Number(p.sell||0);db.sales.push({id:makeId(),date:today(),product:p.name,qty,total,cost:qty*Number(p.cost||0),payment});p.qty=Number(p.qty||0)-qty;if(payment==='Credit')db.credits.push({id:makeId(),date:today(),customer,product:p.name,amount:total,paid:false});saveDB();showBusiness()}
function recordExpense(){const desc=$('expenseDescription').value.trim()||'Expense',amount=Number($('expenseAmount').value);if(amount<=0)return alert('Enter a valid amount.');db.expenses.push({id:makeId(),date:today(),description:desc,amount});saveDB();showBusiness()}
function markPaid(id){const c=db.credits.find(x=>x.id===id);if(!c)return;c.paid=true;c.paidDate=today();saveDB();showCredit()}
function exportDB(){const payload={version:VERSION,exportedAt:new Date().toISOString(),database:db},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`RetailMate_Backup_${today()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
async function restoreDB(file){if(!file)return;try{const parsed=JSON.parse(await file.text()),c=parsed.database||parsed;if(!c||!Array.isArray(c.products)||!Array.isArray(c.sales)||!c.settings)throw new Error();if(confirm('Replace the current RetailMate database with this backup?')){db={settings:{...BASE.settings,...(c.settings||{})},products:c.products||[],sales:c.sales||[],purchases:c.purchases||[],expenses:c.expenses||[],credits:c.credits||[]};saveDB();showDatabase();alert('Backup restored.')}}catch(e){alert('This is not a valid RetailMate backup.')}finally{$('importFile').value=''}}
function clearDB(){if(confirm('Permanently erase all RetailMate records stored on this device?')){db=clone(BASE);saveDB();showDatabase()}}
function bind(){$('sellBtn').addEventListener('click',showSell);$('buyBtn').addEventListener('click',showBuy);$('stockBtn').addEventListener('click',showStock);$('expenseBtn').addEventListener('click',showExpense);$('creditBtn').addEventListener('click',showCredit);$('businessBtn').addEventListener('click',showBusiness);$('databaseBtn').addEventListener('click',showDatabase);$('databaseTopBtn').addEventListener('click',showDatabase);$('importFile').addEventListener('change',e=>restoreDB(e.target.files[0]))}
function init(){try{bind();refreshSummary();showStock();setStatus(`RetailMate v${VERSION} loaded successfully.`,'ok');window.addEventListener('online',refreshSummary);window.addEventListener('offline',refreshSummary)}catch(e){console.error(e);setStatus('App logic failed to load. Please refresh the page.','error')}}
document.addEventListener('DOMContentLoaded',init);
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.unregister()))).catch(()=>{}))}
})();